#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

check_monitor=$(xrandr -q|grep -v disconnected|grep HDMI)
if [[ $? -eq 0 ]];then
  xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 144 --output DP-2 --mode 1920x1080 --left-of HDMI-0
  bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
  bspc monitor DP-2 -d 10
else
  xrandr --output DP-2 --primary --mode 1920x1080
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

~/.config/polybar/launch.sh --hack &
